//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterApiApp.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.DateTime SaleStarts { get; set; }
        public System.DateTime SaleEnds { get; set; }
        public string Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavorite> UserFavorites { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.UserFavorites = new HashSet<UserFavorite>();
        }
    
        public Event(JObject data)
        {
            Name = data["name"].ToString();
            Id = data["id"].ToString();
            Type = data["type"].ToString();
            SaleStarts = DateTime.Parse((string)data["sales"]["public"]["startDateTime"]);
            SaleEnds = DateTime.Parse((string)data["sales"]["public"]["endDateTime"]);
            Status = data["dates"]["status"]["code"].ToString();
        }
        
    }
}
