//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterApiApp.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;

    public partial class Event
    {
        [Key]
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Type { get; set; }
        [Required]
        public System.DateTime SaleStarts { get; set; }
        [Required]
        public System.DateTime SaleEnds { get; set; }
        [Required]
        public string Status { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public virtual ICollection<UserFavorite> UserFavorites { get; set; }

        public Event()
        { }

        public Event(JObject data)
        {
            var start = (string)(data["sales"]["public"]["endDateTime"]);
            var end = (string)data["sales"]["public"]["endDateTime"];

            Name = data["name"].ToString();
            Id = data["id"].ToString();
            Type = data["type"].ToString();
            if (start != null)
            {
                SaleStarts = DateTime.Parse(start);
            }
            if (end != null)
            {
                SaleEnds = DateTime.Parse(end);
            }

            Status = data["dates"]["status"]["code"].ToString();            
        }
        
    }
}
