//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMasterApiApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class UserFavorite
    {
        [Required]
        [Key, Column(Order = 0)]
        public string UserId { get; set; }
        [Required]
        [Key, Column(Order = 1)]
        public string EventId { get; set; }
        public virtual Event Event { get; set; }
    }
}
